name: Push esp-digipot-driver to https://components.espressif.com

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action on

jobs:
  upload_components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v2
        with:
          name: "esp-digipot-driver"
          version: ${{ github.ref_name }}
          namespace: "nichonaugle"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
          repository_url: "https://github.com/nichonaugle/esp-digipot-driver"
          dry_run: yes
