name: Push esp-digipot-driver to https://components.espressif.com

on:
  push:
    tags:
      - "v*"  # Trigger only when a tag starting with "v" is pushed (e.g., v1.0.0)

jobs:
  upload_components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: "esp-digipot-driver: ."
          version: ${{ github.ref_name }}
          namespace: "nichonaugle"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
          repository_url: "https://github.com/nichonaugle/esp-digipot-driver"
          skip_pre_release: false
          dry_run: yes

      - name: Check upload status
        run: |
          JOB_ID="dbc548a7-70ab-47ca-ab48-fcd07404d97f"
          compote component upload-status --job=$JOB_ID
